-- Expand-only Phase 4C. Existing identities, facts and prior SQL remain unchanged.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE ai_feature_flags(code text PRIMARY KEY CHECK(code IN ('search','realtor','description','moderation','duplicates','photo','recommendations','valuation','analytics','support')),enabled boolean NOT NULL DEFAULT false,version integer NOT NULL DEFAULT 1 CHECK(version>0),updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO ai_feature_flags(code) SELECT unnest(ARRAY['search','realtor','description','moderation','duplicates','photo','recommendations','valuation','analytics','support']);
CREATE TABLE ai_budget_days(day date PRIMARY KEY DEFAULT CURRENT_DATE,reserved_micros bigint NOT NULL DEFAULT 0 CHECK(reserved_micros>=0),spent_micros bigint NOT NULL DEFAULT 0 CHECK(spent_micros>=0));
CREATE TABLE ai_usage(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,capability text NOT NULL REFERENCES ai_feature_flags(code),mode text NOT NULL CHECK(mode IN ('ai','fallback')),reason text NOT NULL,attempts integer NOT NULL CHECK(attempts BETWEEN 0 AND 2),latency_ms integer NOT NULL CHECK(latency_ms>=0),cost_micros bigint NOT NULL CHECK(cost_micros>=0),input_tokens integer NOT NULL CHECK(input_tokens>=0),output_tokens integer NOT NULL CHECK(output_tokens>=0),prompt_version text NOT NULL,model_version text NOT NULL,rule_version text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX ai_usage_metrics ON ai_usage(created_at,capability,mode);
CREATE TABLE trust_jobs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),listing_id uuid NOT NULL REFERENCES listings(id),listing_version integer NOT NULL,fact_hash text NOT NULL,rule_version text NOT NULL,state text NOT NULL DEFAULT 'pending' CHECK(state IN ('pending','running','done','dead','stale')),attempts integer NOT NULL DEFAULT 0,available_at timestamptz NOT NULL DEFAULT now(),lease_token uuid,lease_until timestamptz,last_error text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(listing_id,fact_hash,rule_version));
CREATE INDEX trust_jobs_claim ON trust_jobs(available_at,id) WHERE state IN ('pending','running');
CREATE TABLE trust_assessments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),listing_id uuid NOT NULL REFERENCES listings(id),listing_version integer NOT NULL,fact_hash text NOT NULL,rule_version text NOT NULL,findings jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(listing_id,fact_hash,rule_version));
CREATE INDEX trust_assessments_listing ON trust_assessments(listing_id,created_at DESC);
CREATE TABLE duplicate_candidates(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),assessment_id uuid NOT NULL REFERENCES trust_assessments(id),listing_id uuid NOT NULL REFERENCES listings(id),candidate_id uuid NOT NULL REFERENCES listings(id),candidate_version integer NOT NULL,candidate_fact_hash text NOT NULL,confidence numeric(3,2) NOT NULL CHECK(confidence BETWEEN 0 AND 1),reasons jsonb NOT NULL,rule_version text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),CHECK(listing_id<>candidate_id),UNIQUE(assessment_id,candidate_id));
CREATE INDEX duplicate_review_page ON duplicate_candidates(created_at,id);
CREATE TABLE trust_reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),listing_id uuid NOT NULL REFERENCES listings(id),fact_hash text NOT NULL,rule_version text NOT NULL,reviewer_id uuid NOT NULL REFERENCES users(id),decision text NOT NULL CHECK(decision IN ('allow','reject','needs_info')),reason text NOT NULL CHECK(length(reason) BETWEEN 3 AND 2000),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX trust_review_snapshot ON trust_reviews(listing_id,fact_hash,rule_version,created_at DESC,id DESC);
CREATE TABLE duplicate_reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),candidate_id uuid NOT NULL REFERENCES duplicate_candidates(id),reviewer_id uuid NOT NULL REFERENCES users(id),decision text NOT NULL CHECK(decision IN ('confirmed_duplicate','distinct','needs_info')),reason text NOT NULL CHECK(length(reason) BETWEEN 3 AND 2000),created_at timestamptz NOT NULL DEFAULT now());
CREATE FUNCTION immutable_trust_review() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Trust evidence/reviews are immutable'; END $$;
CREATE TRIGGER trust_reviews_immutable BEFORE UPDATE OR DELETE ON trust_reviews FOR EACH ROW EXECUTE FUNCTION immutable_trust_review();
CREATE TRIGGER duplicate_reviews_immutable BEFORE UPDATE OR DELETE ON duplicate_reviews FOR EACH ROW EXECUTE FUNCTION immutable_trust_review();
CREATE TRIGGER trust_assessments_immutable BEFORE UPDATE OR DELETE ON trust_assessments FOR EACH ROW EXECUTE FUNCTION immutable_trust_review();
CREATE TRIGGER duplicate_candidates_immutable BEFORE UPDATE OR DELETE ON duplicate_candidates FOR EACH ROW EXECUTE FUNCTION immutable_trust_review();
CREATE TABLE analytics_daily_keys(day date PRIMARY KEY DEFAULT CURRENT_DATE,secret bytea NOT NULL DEFAULT gen_random_bytes(32));
CREATE TABLE analytics_events(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,schema_version smallint NOT NULL CHECK(schema_version=1),event_key uuid NOT NULL,listing_id uuid NOT NULL REFERENCES listings(id),day date NOT NULL DEFAULT CURRENT_DATE,actor_hash text NOT NULL CHECK(length(actor_hash)=64),kind text NOT NULL CHECK(kind IN ('view','contact_reveal')),promoted boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(day,actor_hash,event_key));
CREATE INDEX analytics_listing_daily ON analytics_events(listing_id,day,kind);
CREATE INDEX analytics_retention ON analytics_events(day);
-- Existing originals are not backfilled or read synchronously. New processing records exact content evidence.
ALTER TABLE media ADD COLUMN content_sha256 text CHECK(content_sha256 ~ '^[0-9a-f]{64}$');
CREATE INDEX media_content_evidence ON media(content_sha256) WHERE content_sha256 IS NOT NULL AND state='ready';
